version: '3'
services:
  myapp:
    container_name: connect420-server
    restart: always
    build: .
    ports:
      - '3001:3001'
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379