name: Test

on:
  push:
    branches:    
      - '*' 
  pull_request:
    branches: 
      - '*'

jobs:

  Jest:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn test

  Lint:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn lint:ci
