name: Test

on:
  push:
    branches:    
      - '*' 
  pull_request:
    branches: 
      - '*'

jobs:

  Jest:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '14.x'

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
